### ISSUE TITLE
Seems to be missing install script on version >= 2

### ISSUE THREAD

**Issue by clagiordano** [brianlmoon/GearmanManager#143]
On new version >= 2.0 seems to be missing install script for gearman-manager as service, what is the right way to install it as a daemon service ?

**Comment by jpirkey** [comment]
In the composer's bin directory (since this should be installed via [composer](https://getcomposer.org/)), there are command line files you can call `pear_manager.php` `pecl_manager.php` ... then it is just a matter of calling one of those with the `-d` option.  

If you are looking for an init script, I have written one that I use, but I don't use the `pear_manager.php` or `pecl_manager.php`; so you'd have to tweak it.  Let me know if you want it anyway.

**Comment by clagiordano** [comment]
Thanks for your answer,

I use gearman-manager v1.0.0 on many production machine, installed with composer but installed as service with the **install.sh** script  **vendor/brianlmoon/gearmanmanager/install/install.sh** and pecl version, I also use global config files located into **/etc/gearman-manager** folder because it is useful for me start a fresh machine with service installed and then I deploy only workers files.
Manual start of the pecl_manager.php with -d option its the same things but you cannot start / stop / restart service withouth killing process and block long running process.
Maybe you can think to port or adapt old install script and related init script?

**Comment by brianlmoon** [comment]
There are too many distributions of Linux and BSD for me to keep up with how to install init scripts in  all of them. And we use daemontools to manager GearmanManager. I will never turn down a PR to get them up to date though.
